### ISSUE TITLE
how to use it with hasql-pool ?

### ISSUE THREAD

**Issue by docteurklein** [cocreature/hasql-notifications#2]
Hello :)

I'm not sure about the status of the repository, but I wondered if I could use this with hasql-pool ?
If so, how?

Thanks :)

**Comment by cocreature** [comment]
In the current state no, @jfischoff has been working on cleaning it up and making it usable. Not sure if that work is already public.

**Comment by jfischoff** [comment]
It's public but I've barely cleaned it up because I have not needed to. I mostly just got test to pass (which was all test file changes I think) and updated it to work with latest stack nightly. 

https://github.com/jfischoff/hasql-notifications

I do plan on cleaning up more when I am closer to releasing the https://github.com/jfischoff/hasql-queue which depends on it.

**Comment by jfischoff** [comment]
I'm not familiar with `hasql-pool` but I assume there is a way to get a connection. That is all you really need to use it.

**Comment by docteurklein** [comment]
thanks a lot for the link :) I wonder how to get a connection out of the pool as well, but it seems the public api only accepts `Hasql.Session`. I'll see what I can do, but in the meantime, I'm having a separate single connection especially for notifications.

PS: My non-working example is here https://github.com/docteurklein/haskell-pg-sse/commit/9ed469777aaaa386a49566dbe4108d95c7bcd00e#diff-f8f3412da88cd4806f23d59fe59ebc3bR102
if you have any idea :)
